openapi: 3.0.3
info: 
  title: SQLPromptSmith API
  version: 0.1.0
  description: AI SQL 提示词生成工具 API
paths:
  /healthz:
    get:
      summary: 健康检查
      description: 检查服务是否正常运行
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
  /api/generate-prompt:
    post:
      summary: 生成 SQL 提示词
      description: 根据任务类型、数据库方言和 Schema 生成 SQL 提示词
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - taskType
                - dialect
              properties:
                taskType:
                  type: string
                  enum: [generate_sql, explain_sql, optimize_sql]
                  description: 任务类型
                dialect:
                  type: string
                  enum: [postgres, mysql]
                  description: 数据库方言
                schema:
                  type: object
                  description: 数据库 Schema（可选）
                question:
                  type: string
                  description: 问题描述（生成 SQL 时必需）
                sql:
                  type: string
                  description: SQL 语句（解释或优化 SQL 时必需）
                constraints:
                  type: object
                  description: 约束条件（可选）
                context:
                  type: object
                  description: 上下文信息（可选）
      responses:
        '200':
          description: 成功生成提示词
          content:
            application/json:
              schema:
                type: object
                properties:
                  promptText:
                    type: string
                    description: 文本格式的提示词
                  promptJson:
                    type: object
                    description: JSON 格式的提示词
                  budget:
                    type: object
                    properties:
                      tokens:
                        type: number
                        description: Token 预算
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: "VALIDATION_ERROR"
                  message:
                    type: string
                    example: "invalid body"
                  details:
                    type: object
                    description: 详细错误信息
  /api/sql/validate:
    post:
      summary: 验证SQL语句
      description: 验证SQL语句的语法、安全性，并提供执行计划和样本结果
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sql
                - connection
              properties:
                sql:
                  type: string
                  description: 要验证的SQL语句
                connection:
                  type: object
                  required:
                    - dialect
                    - database
                  properties:
                    dialect:
                      type: string
                      enum: [postgres, mysql, sqlite, mssql]
                      description: 数据库方言
                    host:
                      type: string
                      description: 数据库主机地址
                    port:
                      type: integer
                      description: 数据库端口
                    database:
                      type: string
                      description: 数据库名称
                    username:
                      type: string
                      description: 用户名
                    password:
                      type: string
                      description: 密码
                    ssl:
                      type: boolean
                      description: 是否使用SSL连接
                options:
                  type: object
                  properties:
                    readonly:
                      type: boolean
                      default: true
                      description: 是否只读模式
                    timeout:
                      type: integer
                      default: 30000
                      minimum: 1000
                      maximum: 300000
                      description: 超时时间（毫秒）
                    maxRows:
                      type: integer
                      default: 1000
                      minimum: 1
                      maximum: 10000
                      description: 最大返回行数
                    explain:
                      type: boolean
                      default: true
                      description: 是否生成执行计划
      responses:
        '200':
          description: 验证成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      isValid:
                        type: boolean
                        description: SQL是否有效
                      syntaxCheck:
                        type: object
                        properties:
                          valid:
                            type: boolean
                            description: 语法是否正确
                          error:
                            type: string
                            description: 语法错误信息
                      executionPlan:
                        type: object
                        properties:
                          plan:
                            type: object
                            description: 执行计划
                          cost:
                            type: number
                            description: 预估成本
                          warnings:
                            type: array
                            items:
                              type: string
                            description: 警告信息
                      sampleResults:
                        type: object
                        properties:
                          columns:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                type:
                                  type: string
                            description: 列信息
                          rows:
                            type: array
                            items:
                              type: array
                            description: 样本数据行
                          executionTime:
                            type: integer
                            description: 执行时间（毫秒）
                      securityCheck:
                        type: object
                        properties:
                          isReadOnly:
                            type: boolean
                            description: 是否为只读操作
                          warnings:
                            type: array
                            items:
                              type: string
                            description: 安全警告
                          blockedOperations:
                            type: array
                            items:
                              type: string
                            description: 被阻止的操作
                      metadata:
                        type: object
                        properties:
                          affectedTables:
                            type: array
                            items:
                              type: string
                            description: 影响的表
                          estimatedRows:
                            type: integer
                            description: 预估行数
                          complexity:
                            type: string
                            enum: [low, medium, high]
                            description: 复杂度
                  requestId:
                    type: string
                    description: 请求ID
        '400':
          description: 请求参数错误
        '500':
          description: 服务器内部错误
  /api/sql/test-connection:
    post:
      summary: 测试数据库连接
      description: 测试数据库连接是否可用
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - connection
              properties:
                connection:
                  type: object
                  required:
                    - dialect
                    - database
                  properties:
                    dialect:
                      type: string
                      enum: [postgres, mysql, sqlite, mssql]
                      description: 数据库方言
                    host:
                      type: string
                      description: 数据库主机地址
                    port:
                      type: integer
                      description: 数据库端口
                    database:
                      type: string
                      description: 数据库名称
                    username:
                      type: string
                      description: 用户名
                    password:
                      type: string
                      description: 密码
                    ssl:
                      type: boolean
                      description: 是否使用SSL连接
      responses:
        '200':
          description: 连接测试结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      connected:
                        type: boolean
                        description: 是否连接成功
                      dialect:
                        type: string
                        description: 数据库方言
                      database:
                        type: string
                        description: 数据库名称
                  requestId:
                    type: string
                    description: 请求ID
        '400':
          description: 请求参数错误
        '500':
          description: 服务器内部错误
  /api/sql/dialects:
    get:
      summary: 获取支持的数据库方言
      description: 获取系统支持的数据库方言列表
      responses:
        '200':
          description: 支持的数据库方言列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: 方言显示名称
                        value:
                          type: string
                          description: 方言值
                        description:
                          type: string
                          description: 方言描述
                        features:
                          type: array
                          items:
                            type: string
                          description: 支持的功能
                  requestId:
                    type: string
                    description: 请求ID